from typing import List, Tuple


class LDScoreParams:
    ld_wind: float = ...
    bedfile: str = ...
    num_of_snp: int = ...
    num_of_org: int = ...
    maf: float = ...
    std_threshold: float = ...
    positions: List[float] = ...

    def __init__(self, *args, **kwargs) -> None: ...


class LDScoreResult:
    l2_add: List[float] = ...
    l2_nadd: List[float] = ...
    mafs: List[float] = ...
    residuals_std: List[float] = ...
    additive_winsizes: List[int] = ...
    non_additive_winsizes: List[int] = ...

def calculate(params: LDScoreParams, *args, **kwargs) -> LDScoreResult: ...