from typing import List

class LDScoreParams:
    ld_wind: float = ...
    bedfile: str = ...
    n_snp: int = ...
    n_org: int = ...
    maf: float = ...
    std_thr: float = ...
    rsq_thr: float = ...
    positions: List[float] = ...

    def __init__(self, *args, **kwargs) -> None: ...


class LDScoreResult:
    l2: List[float] = ...
    l2d: List[float] = ...
    maf: List[float] = ...
    residuals_std: List[float] = ...
    l2_ws: List[int] = ...
    l2d_ws: List[int] = ...
    l2d_wse: List[int] = ...

def calculate(params: LDScoreParams, *args, **kwargs) -> LDScoreResult: ...
